update README

diff --git a/README b/README
--- a/README
+++ b/README
@@ -3,6 +3,7 @@
 This application offers a possibility to turn a Raspberry Pi as a sound device. The application comes with 2 functions: a sound collector and a test tone generator.
 
 List of content
+
 	1.	Configuration Instructions
 	2.	Installation Instructions
 	3.	Operating Instructions
@@ -12,6 +13,7 @@ List of content
 	7.	Credits and Acknowledgement
 
 1.	Configuration Instructions
+
 	RPi Default Booting & Keyboard Layout
 		1.	By default Raspberry Pi boots into X-server (graphic) mode. This increases booting time, but in most cases we don’t use a display with RPi, so the first thing is to disable it. To do so, you need to connect RPi to a display via HDMI-DIV cable. 
 		2.	You also need a USB keyboard for this step. Connect it to your RPi.
@@ -21,8 +23,114 @@ List of content
  		6.	The newer version of Raspbian disables SSH by default, therefore you have to enable it. Navigate to “Interfacing Options” and select “SSH”, Choose “Yes”, Select “Ok”
 		7.	You can also change the keyboard to be “Generic 105 key/Finnish” in “4. Internationalization Options”.
 		8.	Reboot “sudo reboot”
+		
+	Send IP Address by Email 
+	
+		1.	When using Raspberry Pi remotely, you need to know its IP address to connect to it. There are many ways to get the IP address from your Pi. The simplest way to edit “rc.local” file.
+
+		2.	First you need to get a digital signature of your student ID. Please run following command:
+			pi@raspberrypi:~ $ curl --url "http://www.cc.puv.fi/~gc/php/sha_stuID.php" -d "id=e1700346"
+			and you will get:
+			welcome to SHA-1 hashing function
+			Your ID : e1700346
+			SHA hash of your ID: c040f7cde553dc1739ff9b6eebcb1d6f994ce3cb
+		3.	Copy the SHA string to clipboard (in Putty window, ctrl+"Insert" to copy, shift+"Insert" to paste) and run command “sudo nano /etc/rc.local” and add following lines (yellow colored):
+			
+			#!/bin/sh -e
+			#
+			# rc.local
+			#
+			# This script is executed at the end of each multiuser runlevel.
+			# Make sure that the script will "exit 0" on success or any other
+			# value on error.
+			#
+			# In order to enable or disable this script just change the execution
+			# bits.
+			#
+			# By default this script does nothing.
+
+			# Print the IP address
+			sleep 30
+
+			_IP=$(hostname -I) || true
+			if [ "$_IP" ]; then
+			  printf "My IP address is %s\n" "$_IP"
+			  curl --url http://www.cc.puv.fi/~gc/php/sendMailRPi.php -d “email=gc@vamk.fi&from=e1700346&hash=YOURHASH”
+			  curl --url http://www.cc.puv.fi/~gc/php/rasp.php -d "ip=$_IP&name=e1700346"
+			  curl --url http://www.cc.puv.fi/~juma/raspi/rasp_ip.php -d "auth=mckdoe03&name=e1700346&ip=$_IP"
+			fi
+
+			exit 0
+			
+		4.	The line “sleep 30” is to guarantee that IP address is available.
+		5.	The 1st "curl" command sends IP address to your mail box (please change "email" to your email) using a PHP program. The program will verify your ID and signature so please make sure they are correct.
+		6.	The 2nd "curl" command sends IP address to GC’s PHP page and you can see your device name/IP on http://www.cc.puv.fi/~gc/php/rasp.php. 
+
+		7.	The 3rd “curl” command sends IP address to Jukka Matila’s PHP page and you can see your device in his page: http://www.cc.puv.fi/~juma/raspi/. 
+
+	Set USB Sound Card as Default
+			
+		1.	RPi onboard sound card doesn’t have microphone interface. We have to change the default audio device to be USB sound card. 
+		2.	Boot up RPi, and apply the USB sound card. Use “lsusb” command to check if your USB sound card is mounted:
+			pi@raspberrypi:~ $ lsusb
+			Bus 001 Device 004: ID 0d8c:000c C-Media Electronics, Inc. Audio Adapter
+			Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
+			Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp.
+			Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
+		3.	Use “sudo nano /etc/asound.conf”command and put following content to the file:
+			 pcm.!default {
+			  type plug
+			  slave {
+			    pcm "hw:1,0"
+			  }
+			}
+			ctl.!default {
+			    type hw
+			    card 1
+			}
+		4.	Go to your home directory. Use “nano .asoundrc” command and put the same content to the file.
+
+		5.	Run “alsamixer” you should be able to see that USB sound card is the default audio device. For a more sensitive sound detection, it is better to maximize the volume of “Mic”.
+			
+	Fix the Bug of arecord
+	
+		1.	The newest version of Raspbian (a.k.a. Jessie) comes with a new version of alsa-utils (1.0.28), which has a bug while recording: it doesn’t stop even a '—duration' switch is given, and generates lots of useless audio files. To fix this problem, we have to downgrade alsa-util to an earlier version (1.0.25).
+
+		2.	Use “sudo nano /etc/apt/sources.list” command and add the last line:
+			deb http://mirrordirector.raspbian.org/raspbian/ jessie main contrib non-free rpi
+			# Uncomment line below then 'apt-get update' to enable 'apt-get source'
+			#deb-src http://archive.raspbian.org/raspbian/ jessie main contrib non-free rpi
+			deb http://mirrordirector.raspbian.org/raspbian/ wheezy main contrib non-free rpi
+
+		3.	Run “sudo apt-get update”
+
+		4.	Run “sudo aptitude versions alsa-utils” to check if version 1.0.25 of alsa-util is available:
+			pi@raspberrypi:~ $ sudo aptitude versions alsa-utils
+			Package alsa-utils:
+			i   1.0.25-4                                    oldstable                                 500
+			p   1.0.28-1                                    stable                                    500
+
+		5.	Run “sudo apt-get install alsa-utils=1.0.25-4” to downgrade.
+
+		6.	Reboot (if necessary)
+
+		7.	Run “arecord -r44100 -c1 -f S16_LE -d5 test.wav” to test that your microphone is working. You should see a “test.wav” file in the current folder.
+
+		8.	Put earphone on the USB sound card. Run “aplay test.wav” to check that your recording is okay.
+			
+	Install libcurl
+	
+		1.	First use command "ls /usr/include/curl" or "ls /usr/include/arm-linux-gnueabihf/curl" to identify that libcurl library is installed.
+
+		2.	If the folder doesn’t exist. Run “sudo apt-get update” to update the application list.
+
+		3.	Run “sudo apt-get install libcurl3” to install the libcurl3.
+
+		4.	Run “sudo apt-get install libcurl4-openssl-dev” to install the development API of libcurl4.
+
 
 2.	Installation Instructions
+
 	You will get a 16GB microSD card for free from this course. However, the SD card has no operating system pre-installed. You have to do this at home as first homework.
 		1.	Get a laptop/desktop PC with SD-card slot. It may look like as the following picture.
 		2.	If your Laptop/PC does not come with SD-card slot, you need to get an external card-reader and attach it to your PC USB port. A card-reader may look like as following picture.
@@ -36,4 +144,39 @@ List of content
 		10.	Remove the USB device (SD-card) safely from your PC system.
 
 3.	Operating Instructions
-		
+
+	Run command "make" to build the project.
+    	Run command "./sound.out" to run the project. 
+    	The columns which display the recorded sound will appear.
+    	You can also open "testcurl.txt" file to view the results.
+    	To delete execution file, run command "make clean".
+    	The recorded data is also sent to school server for storage.
+	
+4.	List of Files
+
+	README
+	comm.c
+	comm.h
+	main.c
+	makefile
+	screen.c
+	screen.h
+	sound.c
+	sound.h
+	sound.php
+	testcurl.c
+
+5.	Copyright
+
+	This file is created by Nguyen Minh (1800917).
+	
+6.	Contact Info
+	
+	Nguyen Hieu Minh 
+	Phone: 0465453958
+	Mail: hieuminh230696@gmail.com
+	
+7.	Credits and Acknowledgement
+	
+	Author: Nguyen Hieu Minh
+	Instructor: Dr. Gao Chao
